using System;

//Q3. Create a class Employee having private instance member Id, Name Salary, netsalary.  
//    Id should be generated by application Create method calculate_netsalary who’s job is to deduct 10% of TDS. 
//    Declare TDS as static variable. Write method display which will display name and netsalary. This application will be classlibrary. 
//    Declare const int maxemp=3 ie. You can have only 3 employee.
//    Also declare const int maxsal=50000. Use this for validation in constructor if you try to create object with salary 80000,
//    it should display error
//    Create console application and use this class library. Create at least two object of Employee class 

namespace ClassLibrary8
{
    public class Employee
    {
        static int id;
        string name;
        double salary;
        double netsalary;
        static double TDS = 0.1;
        const int maxsal = 50000;
        const int maxemp = 3;
        static Employee()
        {
            Console.WriteLine("AB Software pvt ltd, Mumbai");
        }
        public Employee(string n,double s)
        {   
            if (id < maxemp)
            {
                if (s < maxsal)
                {
                    id = ++id;
                    name = n;
                    salary = s;
                }
                else
                {
                    throw new Exception("Salary should less than 50000");
                }
            }
            else
            {
                throw new Exception("Can not create 4th employeee");
            }
        }
        public void calculate_netSalary()
        {
            netsalary = salary - (salary * TDS);
        }
        public void display()
        {
            Console.WriteLine("Id = {0}....Name = {1}....netSalary = {2}",id,name,netsalary);
        }
        
    }
}
